In [1]:
import numpy as np

In [2]:
a = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])

In [3]:
print(a)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]


In [4]:
print(a.shape)

(2, 2, 3)


In [8]:
b = np.append(a, [[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]])

In [9]:
print(b)

[ 1  2  3  1  2  3  1  2  3  1  2  3  1  2  3  4  5  6  7  8  9 10 11 12]


In [12]:
b = b.reshape(2,2,2,3)

In [13]:
print(b.shape)

(2, 2, 2, 3)


In [14]:
c = np.append(b, [[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]])

In [19]:
c = c.reshape(-1,2,2,3)

In [20]:
print(b.shape)
print(c.shape)

(2, 2, 2, 3)
(3, 2, 2, 3)


In [28]:
d = np.concatenate((a,b,c), axis =0)

ValueError: all the input arrays must have same number of dimensions

In [23]:
print(d.shape)

(5, 2, 2, 3)


In [24]:
print(c)

[[[[ 1  2  3]
   [ 1  2  3]]

  [[ 1  2  3]
   [ 1  2  3]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]


In [25]:
print(b)

[[[[ 1  2  3]
   [ 1  2  3]]

  [[ 1  2  3]
   [ 1  2  3]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]


In [29]:
e = np.concatenate((b,c,d),0)

In [30]:
print(e.shape)

(10, 2, 2, 3)


In [31]:
print(d)

[[[[ 1  2  3]
   [ 1  2  3]]

  [[ 1  2  3]
   [ 1  2  3]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[ 1  2  3]
   [ 1  2  3]]

  [[ 1  2  3]
   [ 1  2  3]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]
